package com.atakmap.android.LoRaBridge.Database;

import android.content.Context;

import androidx.lifecycle.LiveData;

import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * GenericCotRepository
 *
 * Repository layer providing asynchronous access to the generic_cot table.
 * This repository handles non chat CoT messages such as markers, telemetry,
 * and arbitrary event types that may be received from ATAK or decoded from
 * the LoRa physical layer.
 *
 * Responsibilities:
 *   • Insert CoT entries with deduplication
 *   • Provide LiveData queries for UI or analysis components
 *   • Execute database writes on a background thread
 *
 * Notes:
 *   - Uses the same Room database instance as ChatRepository
 *   - Insert operation relies on Room's `@Insert(IGNORE)` to detect duplicates
 *   - For simplicity, asynchronous insertion uses a temporary wait lock
 *     (non blocking for main thread and good enough for plugin behavior)
 */
public class GenericCotRepository {

    /** DAO performing SQL operations on the generic_cot table */
    private final GenericCotDao dao;

    /** Single threaded executor for serial DB writes */
    private static final ExecutorService executor = Executors.newSingleThreadExecutor();

    /**
     * Construct repository using the application scoped Room database.
     */
    public GenericCotRepository(Context ctx) {
        ChatDatabase db = ChatDatabase.getDatabase(ctx);
        this.dao = db.genericCotDao();
    }

    /**
     * Insert entity if not already present.
     *
     * This is a deduplication method based on:
     *   - @Insert(onConflict = IGNORE)
     *   - Insert returns rowId or -1 if ignored
     *
     * Implementation:
     *   • Schedules insert on background thread
     *   • Waits briefly for the result using synchronized lock
     *   • Returns true if a new row was created
     *
     * @param e CoT entity to insert
     * @return true if the row was newly inserted, false if it already existed
     */
    public boolean insertIfAbsent(GenericCotEntity e) {
        final long[] res = { -1 };
        final Object lock = new Object();

        executor.execute(() -> {
            long rowId = dao.insert(e);     // -1 if duplicate
            synchronized (lock) {
                res[0] = rowId;
                lock.notify();
            }
        });

        synchronized (lock) {
            try {
                lock.wait(50);  // Short blocking wait to obtain result
            } catch (InterruptedException ignored) {}
        }

        return res[0] != -1;
    }

    /**
     * Get all CoT messages generated by a specific UID, sorted chronologically.
     *
     * @param uid Sender UID from CoT's <link uid="">
     * @return LiveData <List<GenericCotEntity>>
     */
    public LiveData<List<GenericCotEntity>> getByUid(String uid) {
        return dao.getByUid(uid);
    }

    /**
     * Returns the most recent CoT event in the table.
     */
    public LiveData<GenericCotEntity> latest() {
        return dao.latest();
    }

    /**
     * Delete all entries in generic_cot.
     * Typically used for debugging or plugin reset.
     */
    public void deleteAll() {
        executor.execute(dao::deleteAll);
    }
}
